### PR TITLE
Removes DigestException from BlobStream#writeTo.

### PR DESCRIPTION
**Pull request by coollog**
Realized it doesn't make sense for writeTo to throw a DigestException since the hashing should work fine if the algorithm is implemented correctly.

### CODE REVIEW

**Comment by coollog** [comment]
@elharo @loosebazooka This can be merged in before any of the rest.

**Comment by loosebazooka** [comment]
Do you mean that it would be our fault if the hashing isn't implemented correctly? Should it be an assertion error?

**Comment by coollog** [comment]
@loosebazooka It means it wouldn't be our fault if the hashing isn't implemented correctly. `DescriptorDigest` is where the `DigestException` is thrown, and the intent of that was to catch any invalid digests received over HTTP or from the user side. Digests generated by the JDK should always be valid.

**Comment by coollog** [comment]
Closing since these changes were added in #43

**Pull request closed without merging**
